### ISSUE TITLE
Hm

### ISSUE THREAD

**Issue by MilkAndCookiz** [moonly-dev/ArmorEffect#1]
Hm

**Comment by Hirss** [comment]
ye?

**Comment by YumikoMC** [comment]
Oh un revenant :D

**Comment by MilkAndCookiz** [comment]
Vous savez bien, l'idée et la base du code est carrément de [moi ](github.com/MIlkAndCookiz/ArmorEffect/) depuis 2016 et je n'ai aucun crédit dans le readme...

**Comment by Palente** [comment]
Absolument pas on sais aussi utilisé le php mais pas grave on t'en veux pas

**Comment by MilkAndCookiz** [comment]
Mais vous savez vraisemblablement pas avoir vos propres idées.

**Comment by Palente** [comment]
Je te mentionnerais pour le <?php si c'est comme ça car bon j'utilise le php et tout le monde c'est que tu es le seul a avoir eu l'idée de developper en php

**Comment by MilkAndCookiz** [comment]
On ne vas pas parler de l'idéologie principale du plugin qui à été créer par moi alors et du vol gratuit de cette idée.

**Comment by Palente** [comment]
Arrête de croire que tu es le centre du monde tu nous a pas appris a developper nan? Arrête un peu

**Comment by MilkAndCookiz** [comment]
Je vous ait aidé à une époque *

**Comment by Palente** [comment]
Je t'ai aidé à une époque et?

**Comment by Hirss** [comment]
Tu avez pas quitter minecraft pour garrys mod ?

**Comment by MilkAndCookiz** [comment]
Laisse tomber. Cette communauté et ces membres ne changeront jamais, tous le monde vol tous le monde et personne ne l'ouvre. Allez y continuez à voler toutes les idées de plugins genre [ItemEffects](https://github.com/AnkitM252/ItemEffect) ou même [iProtector](https://github.com/poggit-orphanage/iProtector) . Continuez de toute façons je m'en fous.

**Comment by SteellgoldEstFrancais** [comment]
Bonjour

**Comment by Palente** [comment]
Tu n'est pas le centre du monde cookie on a absolument pas besoin de toi, la communauté en avais besoin et HighLev l'a fait maintenant évite de venir nous souler quand on développe je t'assure on pense absolument pas a roi

**Comment by SteellgoldEstFrancais** [comment]
Il se passe quoi?

**Comment by Seyz123** [comment]
Inutile.
